version: "3.8"

services:
    # image project
    app:
        container_name: laravel-app
        build:
          context: .
          dockerfile: Dockerfile    
          args:
            user: ivo
            uid: 1000
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - rgeasy-network
    # nginx
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "80:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - rgeasy-network

    # db mysql
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - dbvolume:/var/lib/mysql
        ports: 
            - "3306:3306"
        networks: 
            - rgeasy-network

    # queue
    queue:
        container_name: queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - rgeasy-network

    # redis
    redis:
        container_name: redis
        image: redis:latest
        networks: 
            - rgeasy-network

networks: 
    rgeasy-network:
        driver: bridge

volumes:
    dbvolume:
        driver: local